version: '3.8'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    container_name: postgres
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env

  web:
    container_name: foodgram
    image: 'russopelegro/recipes_service:v1'
    restart: always
    command: gunicorn recipes_service.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.19
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
      - ./config/nginx/:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web